name: Deploy
on:
  push:
    branches: [main]

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install nox
          npm install
          pip install scipy
          pip install numpy
          pip install matplotlib
          pip install seaborn 
          pip install pandas
          pip install nilearn
          pip install ipywidgets
          pip install colorspacious
          pip install makeitpop
          pip install xarray
          pip install myst_nb
          pip install ablog
          pip install MyST-Parser
          pip sphinxext-rediraffe
          pip sphinx_book_theme
          pip sphinx_copybutton
          pip sphinx_thebe
          pip install build
          npm install

      - name: Generate documentation
        run: nox -s docs

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/
